version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: admin-chwech

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - "/home/chwech/learn-docker/wordpress/mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: admin-chwech
