version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    volumes:
      - "/home/chwech/docker/wordpress/themes:/var/www/html/wp-content/themes/"
      - "/home/chwech/docker/wordpress/plugins:/var/www/html/wp-content/plugins/"
    environment:
      WORDPRESS_DB_PASSWORD: admin-chwech

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - "/home/chwech/docker/wordpress/mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: admin-chwech

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8000:80"
      - "8001:443"
